name: example
description: "Example for the urdf_parser library"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_gl: ^0.0.21
  three_dart: ^0.0.16
  three_dart_jsm: ^0.0.10
  
  path_provider: ^2.1.1

  urdf_parser: 
    path: ../

  # replace with
  # urdf_parser:
  #   urdf_parser: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/T12/
    - assets/T12/urdf/
    - assets/T12/meshes/
    - assets/T12/urdf/T12.URDF
    - assets/stl/
